### ISSUE TITLE
using node repl to experiment with ProgVis API throws

### ISSUE THREAD

**Issue by zhenchaoli** [pashasadri/progvis-node#2]
looks like if the library is used from node REPL, it'll throw at

https://github.com/pashasadri/progvis-node/blob/91d8c8127b59c918c4d3abc13d162af39c7aff0c/src/progvis.js#L43

because it's passing `null` to `path.parse`

**Comment by pashasadri** [comment]
process.argv is a single element (vs at least 2 when node is invoked normally).  I pushed a fix.
